# netlify.toml

# 1. AMANKAN JALUR ASET (Penting agar React Router tidak dikirimi HTML)
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# 2. PENGALIHAN URL HALAMAN SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 3. KEAMANAN & CACHE ASET
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"