# netlify.toml

# =========================================================================
# ⚠️ SELURUH ATURAN REDIRECTS SUDAH DIPINDAHKAN KE FILE public/_redirects
# JANGAN MENULISKAN [[redirects]] DI SINI AGAR TIDAK TERJADI BENTROKAN KODE
# =========================================================================

# 🛡️ KEAMANAN & OPTIMALISASI CACHE ASET STATIS
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"